# Generated by Django 4.1.7 on 2023-03-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
